### ISSUE TITLE
Is there a working version of a template to use Nextjs and PayloadCMS?

### ISSUE THREAD

**Issue by kamatheuska** [payloadcms/nextjs-custom-server#28]
First of all, thanks to the payload team for such an amazing product. I am in love with PayloadCMS and its great and simple design.

While realizing the nature of Open Source projects, and the amount of work that such a project like Payload CMS might entailed, I do wonder how can it be that, a repository that is on the PayloadCMS project / github, can have the amount of errors I have encountered just trying to make it run.

Is there a working/actual/current version or template to use the amazing PayloadCMS with NextJS? This repo has been painful beyond belief :sweat_smile: :rofl: 

If there isn't, where can one contribute such a thing? After picking my head resolving package dependencies, eslint weird decisions, etc...I think I have somehow a working, non opinionated version of this, very chaotic I am afraid, but at least dependency wise working.

Let me know if thatmight be interesting to the team!
CC: @jmikrut @denolfe 
Nicolas.

**Comment by JarrodMFlesch** [comment]
Hey @kamatheuska I just merged in fixes for all of the headaches you are experiencing. Can you please pull from latest, or possibly even clone a fresh repo and follow the steps outlined in the README. 

Would love to make sure you are able to get up and running 👍

**Comment by valentindiehl** [comment]
Hey @JarrodMFlesch, unfortunately your last update didn't seem to fix it... tried building with the last commit, didn't build because of the already fixed "import { buildConfig } from 'payload/config';" line. 

Tried the new commit after seing this issue here, now I'm able to build. When I try to start it though, it already fails since there is no "index.js" inside the dist/ directory, only a server.js - if I try to start that, I get the "Cannot use import statement outside a module" from the buildConfig line above again. 

```
[00:23:02] INFO (payload): Connected to Mongo server successfully!
[00:23:02] INFO (payload): Starting Payload...
unhandledRejection /PATH_REDACTED/payload.config.ts:1
import { buildConfig } from 'payload/config';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:74:18)
    at wrapSafe (node:internal/modules/cjs/loader:1141:20)
    at Module._compile (node:internal/modules/cjs/loader:1182:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at loadConfig (PATH_REDACTED/node_modules/payload/dist/config/load.js:21:27)
    at BasePayload.init (PATH_REDACTED/node_modules/payload/dist/payload.js:201:33)
```

**Comment by JarrodMFlesch** [comment]
@valentindiehl can you paste your serve script that you are running? Are you running `yarn serve`?

**Comment by valentindiehl** [comment]
@JarrodMFlesch I think I made a mistake, I was running `node dist/server.js` for debugging, that's where I got the error.

If I run the included `yarn serve`, this is what I get:
```
yarn run v1.22.17
$ cross-env NODE_ENV=production PAYLOAD_CONFIG_PATH=dist/payload.config.js node dist/index.js
node:internal/modules/cjs/loader:1042
  throw err;
  ^

Error: Cannot find module 'PATH_REDACTED/dist/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v19.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I also don't see an "index.js" inside my dist directory after running `yarn build`.

If I adjust it to run `dist/server.js`, which actually exists, I get the following (LeftRight is a custom component):
```
yarn run v1.22.17
$ cross-env NODE_ENV=production PAYLOAD_CONFIG_PATH=dist/payload.config.js node dist/server.js
[00:37:19] INFO (payload): Connected to Mongo server successfully!
[00:37:19] INFO (payload): Starting Payload...
unhandledRejection Error: Cannot find module '../blocks/LeftRight'
Require stack:
- /PATH_REDACTED/dist/collections/Page.js
- /PATH_REDACTED/payload.config.js
- /PATH_REDACTED/node_modules/payload/dist/config/load.js
- /PATH_REDACTED/node_modules/payload/dist/payload.js
- /PATH_REDACTED/node_modules/payload/dist/initHTTP.js
- /PATH_REDACTED/node_modules/payload/dist/index.js
- /PATH_REDACTED/dist/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at mod._resolveFilename (/PATH_REDACTED/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/PATH_REDACTED/dist/collections/Page.js:8:35)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/PATH_REDACTED/dist/collections/Page.js',
    '/PATH_REDACTED/dist/payload.config.js',
    '/PATH_REDACTED/node_modules/payload/dist/config/load.js',
    '/PATH_REDACTED/node_modules/payload/dist/payload.js',
    '/PATH_REDACTED/node_modules/payload/dist/initHTTP.js',
    '/PATH_REDACTED/node_modules/payload/dist/index.js',
    '/PATH_REDACTED/dist/server.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm not sure where this is coming from, since everything is working just fine before building using `yarn dev` and also when checking the path from the file in question, the relativ path seems to be correct.

**Comment by valentindiehl** [comment]
I just tested it with a clean project without any custom components which works with the caveat of changing index.js to server.js which makes me wonder if I made a mistake somewhere, but I can't seem to find where I went wrong if everything works without errors and warnings prior to building 🤔

**Comment by valentindiehl** [comment]
@JarrodMFlesch I take everything back and ask for forgiveness, it seemed to have been my stupidity that caused the error. 

I didn't realize the importance of the new parted file structure for blocks (Config.TS / Component.TSX) since the .tsx-files seem to be not correctly accepted as modules. 

When I correctly splitted the files as in the Content/Image/CTA blocks, the build worked correctly and everything is working great. So if anyone else finds him/herself in the same situation: Look at the new file structure for blocks and make sure that everything that's important to Payload is in a ".ts"-file and not a ".tsx"-file to prevent those CommonJS/ESM problems.

**Comment by JarrodMFlesch** [comment]
Awesome glad you were able to get it sorted!

You still had to change your build script to point to server.js though? I think that might be real.

**Comment by enrico-bagattin** [comment]
Hello @JarrodMFlesch, I am experiencing the same problem, if I build the last version there is no "index.js" in the dist folder but only server.js. Then I have another problem when I change it: `unhandledRejection Error: Error: missing secret key. A secret key is needed to secure Payload.`, I have set up correctly the .env and If I run `npm run dev` it works perfectly.

**Comment by JarrodMFlesch** [comment]
@enrico-bagattin @valentindiehl I made that fix to the serve script.

@enrico-bagattin I made a fix to the server file, just pull in the latest changes. Thank you for the report 👍

**Comment by enrico-bagattin** [comment]
@JarrodMFlesch Thank you, I see now that the build command is also missing the `yarn build:next`

**Comment by JarrodMFlesch** [comment]
@enrico-bagattin I just pushed a change that includes that along with an additional script that copies media into the dist folder so it can be served properly. You will need to pull and run `yarn` to install the `copyfiles` dep.

**Comment by kamatheuska** [comment]
@JarrodMFlesch Thanks for the quick answer! The repo now works out of the box when
- clone from master
- use Yarn version `1.22.19`
- Ubuntu 22.04

EDIT: FYI the repo also works for Yarn version `3.3.1`, but needs to migrate from Yarn v1 first.

**Comment by kamatheuska** [comment]
On a side note: 
Executing `yarn` yields the following 

```sh
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "payload > @monaco-editor/react@4.4.6" has unmet peer dependency "monaco-editor@>= 0.25.0 < 1".
warning "payload > express-graphql@0.12.0" has incorrect peer dependency "graphql@^14.7.0 || ^15.3.0".
warning "payload > react-diff-viewer@3.1.1" has incorrect peer dependency "react@^15.3.0 || ^16.0.0".
warning "payload > react-diff-viewer@3.1.1" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0".
warning "payload > react-select@3.2.0" has incorrect peer dependency "react@^16.8.0 || ^17.0.0".
warning "payload > react-select@3.2.0" has incorrect peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "payload > use-context-selector@1.4.1" has unmet peer dependency "scheduler@>=0.19.0".
warning "payload > @monaco-editor/react > @monaco-editor/loader@1.3.2" has unmet peer dependency "monaco-editor@>= 0.21.0 < 1".
warning "payload > react-helmet > react-side-effect@2.1.1" has incorrect peer dependency "react@^16.3.0 || ^17.0.0".
warning "payload > react-select > react-input-autosize@3.0.0" has incorrect peer dependency "react@^16.3.0 || ^17.0.0".
warning " > @trbl/eslint-config@1.2.4" has incorrect peer dependency "eslint-plugin-jest-dom@^2.0.0".
warning " > eslint-plugin-react-hooks@2.5.1" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
warning " > ts-node@10.8.1" has unmet peer dependency "@types/node@*".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 25.43s.
```

Many of this warnings are from packages using older version from React 18. 

Do you think this is worth fixing?
